### PR TITLE
added Taylor window

### PR DESCRIPTION
**Pull request by stringhamc**
I've added in the taylor window functionality. Thanks for building this tool!

### CODE REVIEW

**Comment by stringhamc** [comment]
Slightly wrong normalization fixed. Normalization was added for consistency with the other windows.

**Comment by cokelaer** [comment]
@stringhamc  there is a typo in your implemantation line  1189 with a @ character instead of multiplication I suspect.

**Comment by cokelaer** [comment]
please fix and commit again. thanks

**Comment by stringhamc** [comment]
I've replaced the matrix multiply/dot product operator @ with multiply and sum. Thanks, Craig

**Comment by cokelaer** [comment]
Thanks, Please have a look https://github.com/cokelaer/spectrum/issues/41

**Pull request merged**
