### PR TITLE
Fix loading mydpss under MacOS

### PR DESCRIPTION
**Pull request by juhasch**
Using OSX El Capitan and Anaconda Python 3.5 the library is called `mydpss.cpython-35m-darwin.so` not `mydpss.cpython-35m.so`.

*Update*
Use numpy helper function `load_library` to load library without having to build the library name manually.

### CODE REVIEW

**Comment by bradysalz** [comment]
@cokelaer, can you see if there's anything wrong with this PR? This fix solved my Windows issue too.

**Comment by cokelaer** [comment]
I will test it under my linux box and will merge the request afterwards

**Comment by cokelaer** [comment]
@bradysalz @juhasch 
sorry for the delay and thank you for looking at fixing the mtm lib. 

There is an issue here : there are two  variables defined in your code : libname and lib_name, which is a typo. Indeed the try/except will always fail since libname is not defined

If you could also keep the "easydev" package dependency in the setup: it is used in the doc/

Once done, I can merge thenew pull request.
best

**Comment by juhasch** [comment]
Sorry for the typo and removing easydev. Fixed now.
There also was a typo using `remove_bias` instead of `_remove_bias`

**Comment by cokelaer** [comment]
Merged on the master branch. Thanks

**Pull request merged**
